import "./globals.css";
import React from "react";
import Modal from "@/components/Modal";

export const metadata = {
  title: "DV ToDo App",
  description: "Generated by DV",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Modal />
      </body>
    </html>
  );
}
