import "./globals.css";
import React from "react";

export const metadata = {
  title: "DV ToDo App",
  description: "Generated by DV",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">{children}</body>
    </html>
  );
}
